In [1]:
import itertools
import numpy as np 

In [ ]:
from setupPOMDP import *
from visualizeEnvironment import *

In [23]:
# Actions correspond to E, N, W, S, Stay respectively
allActions = [(1,0), (0,1), (-1,0), (0,-1), (0,0)]

#all location states in grid
numWorlds = 6
gridWidth = 10
gridHeight = 5
gridSet = set(itertools.product(range(gridWidth), range(gridHeight)))

#set of states to remove from each environment
barriersC = {(2,2), (3,2), (4,2), (5,2), (6,2), (7,2), (8,2), (9,2)}
barriersReverseC = {(0,2), (1,2), (2,2), (3,2), (4,2), (5,2), (6,2), (7,2)}
barriersO = {(2,2), (3,2), (4,2), (5,2), (6,2), (7,2)}

#final environment state sets
stateSetC = sorted(list(gridSet.difference(barriersC)))
stateSetReverseC = sorted(list(gridSet.difference(barriersReverseC)))
stateSetO = sorted(list(gridSet.difference(barriersO)))

#goal locations
goal1 = (0,0)
goal2 = (9,4)

#probability of ineffective action
epsilon = .1

In [12]:
np.array(list(gridSet)).shape

(50, 2)

In [34]:
a = np.arange(2)
#a[:] = None
a

array([0, 1])

In [38]:
world322 = np.arange(12).reshape(3,2,2)

In [41]:
world322

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [40]:
world322.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
world322[:,0, :]

array([[0, 1],
       [4, 5],
       [8, 9]])